-- Add debug guest users and user ownership columns to an existing database.
-- Existing rows are assigned to a single legacy debug guest.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debug_guest_id varchar(128) NOT NULL UNIQUE,
    device_fingerprint varchar(128),
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_users_debug_guest_id ON users(debug_guest_id);

INSERT INTO users (debug_guest_id, device_fingerprint, user_agent)
VALUES ('legacy-debug-guest', 'legacy', 'legacy migration')
ON CONFLICT (debug_guest_id) DO NOTHING;

ALTER TABLE knowledge_bases ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS user_id integer;

UPDATE knowledge_bases
SET user_id = (SELECT id FROM users WHERE debug_guest_id = 'legacy-debug-guest')
WHERE user_id IS NULL;

UPDATE sessions
SET user_id = (SELECT id FROM users WHERE debug_guest_id = 'legacy-debug-guest')
WHERE user_id IS NULL;

UPDATE documents
SET user_id = (SELECT id FROM users WHERE debug_guest_id = 'legacy-debug-guest')
WHERE user_id IS NULL;

UPDATE messages
SET user_id = (SELECT id FROM users WHERE debug_guest_id = 'legacy-debug-guest')
WHERE user_id IS NULL;

ALTER TABLE knowledge_bases ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE sessions ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE documents ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE messages ALTER COLUMN user_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS ix_knowledge_bases_user_id ON knowledge_bases(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_documents_user_id ON documents(user_id);
CREATE INDEX IF NOT EXISTS ix_messages_user_id ON messages(user_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'knowledge_bases_user_id_fkey'
    ) THEN
        ALTER TABLE knowledge_bases
            ADD CONSTRAINT knowledge_bases_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'sessions_user_id_fkey'
    ) THEN
        ALTER TABLE sessions
            ADD CONSTRAINT sessions_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'documents_user_id_fkey'
    ) THEN
        ALTER TABLE documents
            ADD CONSTRAINT documents_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_user_id_fkey'
    ) THEN
        ALTER TABLE messages
            ADD CONSTRAINT messages_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;

COMMIT;
